name: Docker Image CI

on:
  push:
    branches: [ master ]
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Docker image
      run: |
        cd $GITHUB_WORKSPACE
        docker --version
        ./docker_setup.sh

    - name: Build image
      run: |
        cd $GITHUB_WORKSPACE
        ./docker_build.sh $GITHUB_REPOSITORY

    - name: Publish Docker images
      run: |
        cd $GITHUB_WORKSPACE
        docker images